### PR TITLE
Update README.md - change order

### PR DESCRIPTION
**Pull request by meirwah**
Update README.md - change order

### CODE REVIEW

**Review by aviadl — APPROVED** [review]

**Comment by dorsha** [comment]
@meirwah can you please check this PR?

**Comment by shilgapira** [comment]
Do you guys want to merge this mission critical PR? Perhaps in the spirit of the new major version? 🫠

**Comment by dorsha** [comment]
@shilgapira can you resolve conflicts?

**Review by omercnet — APPROVED** [review]

**Comment by dorsha** [comment]
Fixed in another PR.

**Pull request closed without merging**
