### PR TITLE
Management User Add Tenant Roles API upgrade

### PR DESCRIPTION
**Pull request by nmacianx**
## Description
Updates the version for the Management User Add Tenant Roles API. 
With this new version, roles will be added to the tenant even if the user does not have access to the tenant. Access to the tenant will be added.

## Must
- [ ] Tests
- [ ] Documentation (if applicable)

### CODE REVIEW

**Comment by dorsha** [comment]
Don't we have test that verify the request sent endpoint?

**Comment by nmacianx** [comment]
@dorsha no, otherwise the CI would fail 🙂

**Comment by dorsha** [comment]
So let's add :)

**Comment by nmacianx** [comment]
@dorsha i don't see a reason for it. No other endpoint has such a thing. Why would this be any different? What's the purpose of adding such a test?

**Comment by dorsha** [comment]
We do have tests that assert that the "called" endpoint is correct (and not v1 for example..):

image


image

**Comment by nmacianx** [comment]
@dorsha added

**Review by dorsha — APPROVED** [review]

**Pull request merged**
